[package]
name = "ibkr-config"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ibkr-auth = { path = "../ibkr-auth" }
ibkr-domain = { path = "../ibkr-domain" }
schemars.workspace = true
serde.workspace = true
url.workspace = true
